package uk.ac.ncl.icos;

import java.io.File;

import org.sbolstandard.core2.ComponentDefinition;
import org.sbolstandard.core2.ModuleDefinition;
import org.sbolstandard.core2.SBOLDocument;
import org.sbolstandard.core2.SequenceOntology;

public class CElementDesign {

	public void createDesign() throws Exception
	{
		SBOLDocument doc=new SBOLDocument();
		doc.setDefaultURIprefix("http://icos.ncl.ac.uk/celement");
		
		ComponentDefinition design=Util.createDNAComponent(doc, "celement", "", "C-element design", SequenceOntology.ENGINEERED_GENE);	
		//Input 1
		ComponentDefinition pmana=Util.createDNAComponent(doc, "pmana", "pmanA", "pmanPA-yjdF promoter ", SequenceOntology.PROMOTER,
				"AAAGCAGGGATTATTCCTTGCTTTTTTTGTTATAGGGAAAAATGCCTTTATTACCGGAACCTATGGTAAAAAAAGCGATTTTAATGAGCTGATTTCGGTATACAGT");
		ComponentDefinition rbsmana=Util.createDNAComponent(doc, "rbsman", "RBS_manA", "manA RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"AGCGGGGGATTTTC");		
		ComponentDefinition beti=Util.createDNAComponent(doc, "beti", "betI", "betI CDS", SequenceOntology.CDS,
				"ATGCCGAAACTGGGTATGCAGAGCATTCGTCGTCGTCAGCTGATTGATGCAACCCTGGAAGCAATTAATGAAGTTGGTATGCATGATGCAACCATTGCACAGATTGCACGTCGTGCCGGTGTTAGCACCGGTATTATTAGCCATTATTTCCGCGATAAAAACGGTCTGCTGGAAGCAACCATGCGTGATATTACCAGCCAGCTGCGTGATGCAGTTCTGAATCGTCTGCATGCACTGCCGCAGGGTAGCGCAGAACAGCGTCTGCAGGCAATTGTTGGTGGTAATTTTGATGAAACCCAGGTTAGCAGCGCAGCAATGAAAGCATGGCTGGCATTTTGGGCAAGCAGCATGCATCAGCCGATGCTGTATCGTCTGCAGCAGGTTAGCAGTCGTCGTCTGCTGAGCAATCTGGTTAGCGAATTTCGTCGTGAACTGCCTCGTGAACAGGCACAAGAGGCAGGTTATGGTCTGGCAGCACTGATTGATGGTCTGTGGCTGCGTGCAGCACTGAGCGGTAAACCGCTGGATAAAACCCGTGCAAATAGCCTGACCCGTCATTTTATCACCCAGCATCTGCCGACCGATTAA");
		ComponentDefinition rfp=Util.createDNAComponent(doc, "rfp", "rfp", "BBa_E1010", SequenceOntology.CDS,
				"atggcttcctccgaagacgttatcaaagagttcatgcgtttcaaagttcgtatggaaggttccgttaacggtcacgagttcgaaatcgaaggtgaaggtgaaggtcgtccgtacgaaggtacccagaccgctaaactgaaagttaccaaaggtggtccgctgccgttcgcttgggacatcctgtccccgcagttccagtacggttccaaagcttacgttaaacacccggctgacatcccggactacctgaaactgtccttcccggaaggtttcaaatgggaacgtgttatgaacttcgaagacggtggtgttgttaccgttacccaggactcctccctgcaagacggtgagttcatctacaaagttaaactgcgtggtaccaacttcccgtccgacggtccggttatgcagaaaaaaaccatgggttgggaagcttccaccgaacgtatgtacccggaagacggtgctctgaaaggtgaaatcaaaatgcgtctgaaactgaaagacggtggtcactacgacgctgaagttaaaaccacctacatggctaaaaaaccggttcagctgccgggtgcttacaaaaccgacatcaaactggacatcacctcccacaacgaagactacaccatcgttgaacagtacgaacgtgctgaaggtcgtcactccaccggtgcttaataa");
		ComponentDefinition ter1=Util.createDNAComponent(doc, "ter1", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		//Input 2
		ComponentDefinition pyxeb=Util.createDNAComponent(doc, "pyxeb", "pyxeB", "pyxeB promoter Fur interaction site from BacillusRegNet + sides NC_000964.3", SequenceOntology.PROMOTER, 
				"AAAAACTTTCTCCCTTAAAAATAGTGATAGACGGAGAACAGGTTTCTTGCTATATTATTAATTGATAATGATAATCATTACTAATCTATTGAGA");		
		ComponentDefinition rbsyxeb=Util.createDNAComponent(doc, "rbsyxeb", "RBS_yxeB", "yxeB RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"TACATAGTGGGAGGGTTCTTG");
		ComponentDefinition litr=Util.createDNAComponent(doc, "litr", "litR", "litR CDS", SequenceOntology.CDS,
				"ATGGATACCATTCAGAAACGTCCGCGTACCCGTCTGAGTCCGGAAAAACGTAAAGAACAGCTGCTGGATATTGCCATTGAAGTTTTTAGCCAGCGTGGTATTGGTCGTGGTGGTCATGCAGATATTGCAGAAATTGCACAGGTTAGCGTTGCAACCGTGTTTAACTATTTTCCGACCCGTGAAGATCTGGTTGATGATGTTCTGAACAAAGTGGAAAACGAGTTTCACCAGTTCATCAATAACAGCATTAGCCTGGATCTGGATGTTCGTAGCAATCTGAATACCCTGCTGCTGAACATTATTGATAGCGTTCAGACCGGCAACAAATGGATTAAAGTTTGGTTTGAATGGTCAACCAGCACCCGTGATGAAGTTTGGCCTCTGTTTCTGAGCACCCATAGCAATACCAATCAGGTGATCAAAACCATGTTTGAAGAGGGTATTGAACGCAATGAAGTGTGCAATGATCATACACCGGAAAATCTGACCAAAATGCTGCATGGTATTTGCTATAGCGTGTTTATTCAGGCCAATCGTAATAGCAGCAGCGAAGAAATGGAAGAAACCGCAAATTGCTTTCTGAATATGCTGTGCATCTACAAATAA");
		ComponentDefinition cfp=Util.createDNAComponent(doc, "cfp", "cfp", "cfp CDS AF545829.1", SequenceOntology.CDS,
				"ATGGATCCATTGGTCAACGGAAATTTGAAGATAAAGATGTTCATGAACGGGAGCGTTAACAAACACAAATTTAAGTGCGAAGCAGAAGGAGAAGGAAATATACACAGTGGAACCCATATCATGAAAATAACAGTGACTGAGGGTGGTCCTTTGCCTTTTGCTTTTGACATCCTGTCACGAACATTCTGTTATGGCCACAAAATGTTTTTGGACAACTCTGGAAACATTCCAGATTTCTTTAAGCAGTCTTTGAAAGATGGATACAGTTGGGAAAGAGAAACCACCTATGAAGATGGAGGGGTCCTGAATTCTAAACAGAAGCACACTCTAAAAGGTGATTGCATTACTACCTACTCGGAAGTCACTGGCACATTCCCTCCCAATGGCCCTGTCATGAAAAAGAAGACACTTGGTTGGGAGCCATCTTGCGAGATGGTCATTCCACGTGATGGTGGGCTCATCATGTACGACAACATTGCACTAAAACTTGATGATGATCATGGTGGTCATCTCACTGGCAATTTCAAGGCAACGTACAAGTCAAATAACCCGAACATAAATCTCCCCAAACACCATTTTGTGGAAAATCGCGTGGAGATGCTGGAGGGACGTGATGGTGGCAATTATGTGAAGCTGCATGAGAGAAATAAAGCCAGATACTCAGCTTTGGAAAGCGAACTGGCCAAAAAATGA");
		ComponentDefinition ter2=Util.createDNAComponent(doc, "ter2", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");

		// Transcription unit 1
		ComponentDefinition pbeti1=Util.createDNAComponent(doc, "pbeti1", "pbetI", "betI promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaattgacaATTGATTGGACGTTCAATATAAtgctagctactagag");		
		ComponentDefinition rbsbeti=Util.createDNAComponent(doc, "rbsbeti", "RBS_betI", "betI RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"GCTACGACTTGCTCATTTGACAGAGGATAACTACTA");
		ComponentDefinition amtr=Util.createDNAComponent(doc, "amtr", "amtR", "amtR CDS", SequenceOntology.CDS,
				"ATGGCAGGCGCAGTTGGTCGTCCGCGTCGTAGTGCACCGCGTCGTGCAGGTAAAAATCCGCGTGAAGAAATTCTGGATGCAAGCGCAGAACTGTTTACCCGTCAGGGTTTTGCAACCACCAGTACCCATCAGATTGCAGATGCAGTTGGTATTCGTCAGGCAAGCCTGTATTATCATTTTCCGAGCAAAACCGAAATCTTTCTGACCCTGCTGAAAAGCACCGTTGAACCGAGCACCGTTCTGGCAGAAGATCTGAGCACCCTGGATGCAGGTCCGGAAATGCGTCTGTGGGCAATTGTTGCAAGCGAAGTTCGTCTGCTGCTGAGCACCAAATGGAATGTTGGTCGTCTGTATCAGCTGCCGATTGTTGGTAGCGAAGAATTTGCAGAATATCATAGCCAGCGTGAAGCACTGACCAATGTTTTTCGTGATCTGGCAACCGAAATTGTTGGTGATGATCCGCGTGCAGAACTGCCGTTTCATATTACCATGAGCGTTATTGAAATGCGTCGCAATGATGGTAAAATTCCGAGTCCGCTGAGCGCAGATAGCCTGCCGGAAACCGCAATTATGCTGGCAGATGCAAGCCTGGCAGTTCTGGGTGCACCGCTGCCTGCAGATCGTGTTGAAAAAACCCTGGAACTGATTAAACAGGCAGATGCAAAATAA");
		ComponentDefinition ter3=Util.createDNAComponent(doc, "ter3", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Transcription unit 2
		ComponentDefinition plitr1=Util.createDNAComponent(doc, "plitr1", "plitR", "plitR promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaatTGACAAATTTATAAATTGTCAgtataatgctagctactagag");		
		ComponentDefinition rbslitr1=Util.createDNAComponent(doc, "rbsplitr1", "RBS_litR", "litR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTTCACACAGGGTTTTCACACAGGAGAAACCTCG");
		ComponentDefinition amtr2=Util.createDNAComponent(doc, "amtr2", "amtR2", "amtR2 CDS", SequenceOntology.CDS,
				"ATGGCAGGCGCAGTTGGTCGTCCGCGTCGTAGTGCACCGCGTCGTGCAGGTAAAAATCCGCGTGAAGAAATTCTGGATGCAAGCGCAGAACTGTTTACCCGTCAGGGTTTTGCAACCACCAGTACCCATCAGATTGCAGATGCAGTTGGTATTCGTCAGGCAAGCCTGTATTATCATTTTCCGAGCAAAACCGAAATCTTTCTGACCCTGCTGAAAAGCACCGTTGAACCGAGCACCGTTCTGGCAGAAGATCTGAGCACCCTGGATGCAGGTCCGGAAATGCGTCTGTGGGCAATTGTTGCAAGCGAAGTTCGTCTGCTGCTGAGCACCAAATGGAATGTTGGTCGTCTGTATCAGCTGCCGATTGTTGGTAGCGAAGAATTTGCAGAATATCATAGCCAGCGTGAAGCACTGACCAATGTTTTTCGTGATCTGGCAACCGAAATTGTTGGTGATGATCCGCGTGCAGAACTGCCGTTTCATATTACCATGAGCGTTATTGAAATGCGTCGCAATGATGGTAAAATTCCGAGTCCGCTGAGCGCAGATAGCCTGCCGGAAACCGCAATTATGCTGGCAGATGCAAGCCTGGCAGTTCTGGGTGCACCGCTGCCTGCAGATCGTGTTGAAAAAACCCTGGAACTGATTAAACAGGCAGATGCAAAATAA");
		ComponentDefinition ter4=Util.createDNAComponent(doc, "ter4", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Transcription unit 3
		ComponentDefinition pamtr=Util.createDNAComponent(doc, "pamtr", "pamtR", "amtR promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaattgacagTTTCTATCGATCTATAGATAATgctagctactagag");		
		ComponentDefinition rbsamtr1=Util.createDNAComponent(doc, "rbsamtr1", "RBS_amtR", "amtR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGAGAATACTAG");
		ComponentDefinition srpr1=Util.createDNAComponent(doc, "srpr1", "srpR", "srpR CDS", SequenceOntology.CDS,
				"ATGGCACGTAAAACCGCAGCAGAAGCAGAAGAAACCCGTCAGCGTATTATTGATGCAGCACTGGAAGTTTTTGTTGCACAGGGTGTTAGTGATGCAACCCTGGATCAGATTGCACGTAAAGCCGGTGTTACCCGTGGTGCAGTTTATTGGCATTTTAATGGTAAACTGGAAGTTCTGCAGGCAGTTCTGGCAAGCCGTCAGCATCCGCTGGAACTGGATTTTACACCGGATCTGGGTATTGAACGTAGCTGGGAAGCAGTTGTTGTTGCAATGCTGGATGCAGTTCATAGTCCGCAGAGCAAACAGTTTAGCGAAATTCTGATTTATCAGGGTCTGGATGAAAGCGGTCTGATTCATAATCGTATGGTTCAGGCAAGCGATCGTTTTCTGCAGTATATTCATCAGGTTCTGCGTCATGCAGTTACCCAGGGTGAACTGCCGATTAATCTGGATCTGCAGACCAGCATTGGTGTTTTTAAAGGTCTGATTACCGGTCTGCTGTATGAAGGTCTGCGTAGCAAAGATCAGCAGGCACAGATTATCAAAGTTGCACTGGGTAGCTTTTGGGCACTGCTGCGTGAACCGCCTCGTTTTCTGCTGTGTGAAGAAGCACAGATTAAACAGGTGAAATCCTTCGAATAA");
		ComponentDefinition rbsamtr2=Util.createDNAComponent(doc, "rbsamtr2", "RBS_amtR", "amtR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGAGAATACTAG");
		ComponentDefinition mcbr1=Util.createDNAComponent(doc, "mcbr1", "mcbR", "mcbR CDS", SequenceOntology.CDS,
				"ATGGCAGCAAGCGCAAGCGGTAAAAGCAAAACCAGTGCCGGTGCAAATCGTCGTCGTAATCGTCCGAGTCCGCGTCAGCGTCTGCTGGATAGCGCAACCAACCTGTTTACCACCGAAGGTATTCGTGTGATTGGTATTGATCGTATTCTGCGTGAAGCAGATGTTGCAAAAGCAAGCCTGTATAGCCTGTTTGGTAGCAAAGATGCACTGGTTATTGCCTATCTGGAAAATCTGGATCAGCTGTGGCGTGAAGCATGGCGTGAACGTACCGTTGGTATGAAAGATCCGGAAGATAAAATCATTGCGTTCTTTGATCAGTGCATCGAAGAAGAACCGGAAAAAGATTTTCGCGGTAGCCATTTTCAGAATGCAGCAAGCGAATATCCGCGTCCGGAAACCGATAGCGAAAAAGGTATTGTTGCAGCAGTTCTGGAACATCGTGAATGGTGTCATAAAACCCTGACCGATCTGCTGACCGAAAAAAATGGTTATCCGGGTACAACCCAGGCAAATCAGCTGCTGGTTTTTCTGGATGGTGGTCTGGCAGGTAGCCGTCTGGTTCATAACATTAGTCCGCTGGAAACCGCACGTGATCTGGCACGTCAGCTGCTGAGCGCACCGCCTGCAGATTATAGCATTTAA");
		ComponentDefinition ter5=Util.createDNAComponent(doc, "ter5", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Transcription unit 4
		ComponentDefinition psrpr=Util.createDNAComponent(doc, "psrpr", "psrpR", "srpR promoter", SequenceOntology.PROMOTER, 
				"GGAACAAACGTTTGATTGAcagctagctcagtcctaggtataatgctagctactagag");		
		ComponentDefinition rbssrpr1=Util.createDNAComponent(doc, "rbssrpr1", "RBS_srpR", "srpR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGGATACGAACTACTAG");
		ComponentDefinition mcbr2=Util.createDNAComponent(doc, "mcbr2", "mcbR", "mcbR CDS", SequenceOntology.CDS,
				"ATGGCAGCAAGCGCAAGCGGTAAAAGCAAAACCAGTGCCGGTGCAAATCGTCGTCGTAATCGTCCGAGTCCGCGTCAGCGTCTGCTGGATAGCGCAACCAACCTGTTTACCACCGAAGGTATTCGTGTGATTGGTATTGATCGTATTCTGCGTGAAGCAGATGTTGCAAAAGCAAGCCTGTATAGCCTGTTTGGTAGCAAAGATGCACTGGTTATTGCCTATCTGGAAAATCTGGATCAGCTGTGGCGTGAAGCATGGCGTGAACGTACCGTTGGTATGAAAGATCCGGAAGATAAAATCATTGCGTTCTTTGATCAGTGCATCGAAGAAGAACCGGAAAAAGATTTTCGCGGTAGCCATTTTCAGAATGCAGCAAGCGAATATCCGCGTCCGGAAACCGATAGCGAAAAAGGTATTGTTGCAGCAGTTCTGGAACATCGTGAATGGTGTCATAAAACCCTGACCGATCTGCTGACCGAAAAAAATGGTTATCCGGGTACAACCCAGGCAAATCAGCTGCTGGTTTTTCTGGATGGTGGTCTGGCAGGTAGCCGTCTGGTTCATAACATTAGTCCGCTGGAAACCGCACGTGATCTGGCACGTCAGCTGCTGAGCGCACCGCCTGCAGATTATAGCATTTAA");
		ComponentDefinition rbssrpr2=Util.createDNAComponent(doc, "rbssrpr2", "RBS_srpR", "srpR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGGATACGAACTACTAG");
		ComponentDefinition icar1=Util.createDNAComponent(doc, "icar1", "icaR", "icaR CDS", SequenceOntology.CDS,
				"ATGAAAGACAAAATTATCGATAACGCCATCACCCTGTTTAGCGAAAAAGGTTATGACGGCACCACCCTGGATGATATTGCAAAAAGCGTGAACATCAAAAAAGCCAGCCTGTATTATCACTTTGATAGCAAAAAAAGCATCTACGAGCAGAGCGTTAAATGCTGTTTCGATTATCTGAACAACATCATCATGATGAACCAGAACAAAAGCAACTATAGCATCGATGCCCTGTATCAGTTTCTGTTTGAGTTCATCTTCGATATCGAGGAACGCTATATTCGTATGTATGTTCAGCTGAGCAACACACCGGAAGAATTTTCAGGTAACATTTATGGCCAGATCCAGGATCTGAATCAGAGCCTGAGCAAAGAAATCGCCAAATTCTATGACGAAAGCAAAATCAAAATGACCAAAGAGGACTTCCAGAATCTGATTCTGCTGTTTCTGGAAAGCTGGTATCTGAAAGCCAGCTTTAGCCAGAAATTTGGTGCAGTTGAAGAAAGCAAAAGCCAGTTTAAAGATGAGGTTTATAGCCTGCTGAACATCTTTCTGAAGAAATAA");
		ComponentDefinition ter6=Util.createDNAComponent(doc, "ter6", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		ComponentDefinition rbsmcbr2=Util.createDNAComponent(doc, "rbsmcbr2", "RBS_mcbR", "mcbR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTAGGAGAAATACTAG");
		
		// Transcription unit 5
		ComponentDefinition picar=Util.createDNAComponent(doc, "picar", "picaR", "sicaR promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaattgacaaTTCACCTACCTTTCGTTAGGTTAGGTTGTtactagag");		
		ComponentDefinition rbsicar1=Util.createDNAComponent(doc, "rbsicar1", "RBS_icaR", "icaR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTTCACACAGGGGCCGG");
		ComponentDefinition amtr3=Util.createDNAComponent(doc, "amtr3", "amtR3", "amtR3 CDS", SequenceOntology.CDS,
				"ATGGCAGGCGCAGTTGGTCGTCCGCGTCGTAGTGCACCGCGTCGTGCAGGTAAAAATCCGCGTGAAGAAATTCTGGATGCAAGCGCAGAACTGTTTACCCGTCAGGGTTTTGCAACCACCAGTACCCATCAGATTGCAGATGCAGTTGGTATTCGTCAGGCAAGCCTGTATTATCATTTTCCGAGCAAAACCGAAATCTTTCTGACCCTGCTGAAAAGCACCGTTGAACCGAGCACCGTTCTGGCAGAAGATCTGAGCACCCTGGATGCAGGTCCGGAAATGCGTCTGTGGGCAATTGTTGCAAGCGAAGTTCGTCTGCTGCTGAGCACCAAATGGAATGTTGGTCGTCTGTATCAGCTGCCGATTGTTGGTAGCGAAGAATTTGCAGAATATCATAGCCAGCGTGAAGCACTGACCAATGTTTTTCGTGATCTGGCAACCGAAATTGTTGGTGATGATCCGCGTGCAGAACTGCCGTTTCATATTACCATGAGCGTTATTGAAATGCGTCGCAATGATGGTAAAATTCCGAGTCCGCTGAGCGCAGATAGCCTGCCGGAAACCGCAATTATGCTGGCAGATGCAAGCCTGGCAGTTCTGGGTGCACCGCTGCCTGCAGATCGTGTTGAAAAAACCCTGGAACTGATTAAACAGGCAGATGCAAAATAA");
		ComponentDefinition rbsicar2=Util.createDNAComponent(doc, "rbsicar2", "RBS_icaR", "icaR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTTCACACAGGGGCCGG");
		ComponentDefinition srpr2=Util.createDNAComponent(doc, "srpr2", "srpR", "srpR CDS", SequenceOntology.CDS,
				"ATGGCACGTAAAACCGCAGCAGAAGCAGAAGAAACCCGTCAGCGTATTATTGATGCAGCACTGGAAGTTTTTGTTGCACAGGGTGTTAGTGATGCAACCCTGGATCAGATTGCACGTAAAGCCGGTGTTACCCGTGGTGCAGTTTATTGGCATTTTAATGGTAAACTGGAAGTTCTGCAGGCAGTTCTGGCAAGCCGTCAGCATCCGCTGGAACTGGATTTTACACCGGATCTGGGTATTGAACGTAGCTGGGAAGCAGTTGTTGTTGCAATGCTGGATGCAGTTCATAGTCCGCAGAGCAAACAGTTTAGCGAAATTCTGATTTATCAGGGTCTGGATGAAAGCGGTCTGATTCATAATCGTATGGTTCAGGCAAGCGATCGTTTTCTGCAGTATATTCATCAGGTTCTGCGTCATGCAGTTACCCAGGGTGAACTGCCGATTAATCTGGATCTGCAGACCAGCATTGGTGTTTTTAAAGGTCTGATTACCGGTCTGCTGTATGAAGGTCTGCGTAGCAAAGATCAGCAGGCACAGATTATCAAAGTTGCACTGGGTAGCTTTTGGGCACTGCTGCGTGAACCGCCTCGTTTTCTGCTGTGTGAAGAAGCACAGATTAAACAGGTGAAATCCTTCGAATAA");
		ComponentDefinition ter7=Util.createDNAComponent(doc, "ter7", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		ComponentDefinition rbsamtr3=Util.createDNAComponent(doc, "rbsamtr3", "RBS_amtR", "amtR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGAGAATACTAG");
		
		// Transcription unit 6
		ComponentDefinition pliag=Util.createDNAComponent(doc, "pliag", "pliaG", "pliaG constitutive promoter BBa_K823000", SequenceOntology.PROMOTER, 
				"caaaaatcagaccagacaaaagcggcaaatgaataagcggaacggggaaggatttgcggtcaagtccttcccttccgcacgtatcaattcgcaagcttttcctttataatagaatgaatga");	
		ComponentDefinition pbeti2=Util.createDNAComponent(doc, "pbeti2", "betI operator", "betI operator", SequenceOntology.OPERATOR, 
				"ATTGATTGGACGTTCAATATAA");	
		ComponentDefinition plitr2=Util.createDNAComponent(doc, "plitr2", "litR operator", "plitR operator", SequenceOntology.OPERATOR, 
				"TGACAAATTTATAAATTGTCA");	
		ComponentDefinition rbslitr2=Util.createDNAComponent(doc, "rbsplitr2", "RBS_litR", "litR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTTCACACAGGGTTTTCACACAGGAGAAACCTCG");
		ComponentDefinition phlf=Util.createDNAComponent(doc, "phlf", "phlF", "phlF CDS", SequenceOntology.CDS,
				"ATGGCACGTACCCCGAGCCGTAGCAGCATTGGTAGCCTGCGTAGTCCGCATACCCATAAAGCAATTCTGACCAGCACCATTGAAATCCTGAAAGAATGTGGTTATAGCGGTCTGAGCATTGAAAGCGTTGCACGTCGTGCCGGTGCAAGCAAACCGACCATTTATCGTTGGTGGACCAATAAAGCAGCACTGATTGCCGAAGTGTATGAAAATGAAAGCGAACAGGTGCGTAAATTTCCGGATCTGGGTAGCTTTAAAGCCGATCTGGATTTTCTGCTGCGTAATCTGTGGAAAGTTTGGCGTGAAACCATTTGTGGTGAAGCATTTCGTTGTGTTATTGCAGAAGCACAGCTGGACCCTGCAACCCTGACCCAGCTGAAAGATCAGTTTATGGAACGTCGTCGTGAGATGCCGAAAAAACTGGTTGAAAATGCCATTAGCAATGGTGAACTGCCGAAAGATACCAATCGTGAACTGCTGCTGGATATGATTTTTGGTTTTTGTTGGTATCGCCTGCTGACCGAACAGCTGACCGTTGAACAGGATATTGAAGAATTTACCTTCCTGCTGATTAATGGTGTTTGTCCGGGTACACAGCGTTAA");
		ComponentDefinition ter8=Util.createDNAComponent(doc, "ter8", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Transcription unit 7
		ComponentDefinition pphlf=Util.createDNAComponent(doc, "pphlf", "pphlF", "phlF promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaattgacATGATACGAAACGTACCGTATCGTTAAGGTtactagag");		
		ComponentDefinition rbsphlf=Util.createDNAComponent(doc, "rbsphlf", "RBS_phlF", "phlF RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGGGAGAAATACTAG");
		ComponentDefinition qacr=Util.createDNAComponent(doc, "qacr", "qacR", "qacR CDS", SequenceOntology.CDS,
				"ATGAACCTGAAAGATAAAATTCTGGGCGTTGCCAAAGAACTGTTTATCAAAAATGGCTATAACGCAACCACCACCGGTGAAATTGTTAAACTGAGCGAAAGCAGCAAAGGCAATCTGTATTATCACTTTAAAACCAAAGAGAACCTGTTTCTGGAAATCCTGAACATCGAAGAAAGCAAATGGCAAGAGCAGTGGAAAAAAGAACAAATCAAATGCAAAACCAACCGCGAGAAATTCTATCTGTATAATGAACTGAGCCTGACCACCGAATATTACTATCCGCTGCAGAATGCCATCATCGAGTTTTATACCGAGTACTATAAAACCAACAGCATCAACGAGAAAATGAACAAACTGGAAAACAAATACATCGATGCCTACCACGTGATCTTTAAAGAAGGTAATCTGAACGGCGAATGGTGCATTAATGATGTTAATGCCGTGAGCAAAATTGCAGCAAATGCCGTTAATGGCATTGTTACCTTTACCCATGAGCAGAATATCAACGAACGCATTAAACTGATGAACAAATTCAGCCAGATCTTTCTGAATGGCCTGAGCAAATAA");
		ComponentDefinition ter9=Util.createDNAComponent(doc, "ter9", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Transcription unit 8
		ComponentDefinition pqacr=Util.createDNAComponent(doc, "pqacr", "pqacR", "qacR promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaattgacagctagctcagtcctaCTTTAGTATAGAGACTGAGCGGTCGGTCTATAtac");		
		ComponentDefinition rbsqacr=Util.createDNAComponent(doc, "rbsqacr", "RBS_qacR", "qacR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"GCCATGCCATTGGCTTTTCACACAGGACACCGGTTAG");
		ComponentDefinition icar2=Util.createDNAComponent(doc, "icar2", "icaR", "icaR CDS", SequenceOntology.CDS,
				"ATGAAAGACAAAATTATCGATAACGCCATCACCCTGTTTAGCGAAAAAGGTTATGACGGCACCACCCTGGATGATATTGCAAAAAGCGTGAACATCAAAAAAGCCAGCCTGTATTATCACTTTGATAGCAAAAAAAGCATCTACGAGCAGAGCGTTAAATGCTGTTTCGATTATCTGAACAACATCATCATGATGAACCAGAACAAAAGCAACTATAGCATCGATGCCCTGTATCAGTTTCTGTTTGAGTTCATCTTCGATATCGAGGAACGCTATATTCGTATGTATGTTCAGCTGAGCAACACACCGGAAGAATTTTCAGGTAACATTTATGGCCAGATCCAGGATCTGAATCAGAGCCTGAGCAAAGAAATCGCCAAATTCTATGACGAAAGCAAAATCAAAATGACCAAAGAGGACTTCCAGAATCTGATTCTGCTGTTTCTGGAAAGCTGGTATCTGAAAGCCAGCTTTAGCCAGAAATTTGGTGCAGTTGAAGAAAGCAAAAGCCAGTTTAAAGATGAGGTTTATAGCCTGCTGAACATCTTTCTGAAGAAATAA");
		ComponentDefinition ter10=Util.createDNAComponent(doc, "ter10", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Transcription unit 9
		ComponentDefinition pmcbr=Util.createDNAComponent(doc, "pmcbr", "pmcbR", "mcbR promoter", SequenceOntology.PROMOTER, 
				"gattcgttaccaattgacaATAGAAAGATCTGTCTAtataatgctagctactagag");		
		ComponentDefinition rbsmcbr=Util.createDNAComponent(doc, "rbsmcbr", "RBS_mcbR", "mcbR RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTAGGAGAAATACTAG");
		ComponentDefinition psra=Util.createDNAComponent(doc, "psra", "psrA", "psrA CDS", SequenceOntology.CDS,
				"ATGGCACAGAGCGAAACCGTTGAACGTATTCTGGATGCAGCAGAACAGCTGTTTGCAGAACGTGGTTTTGCAGAAACCAGCCTGCGTCTGATTACCAGCAAAGCCGGTGTTAATCTGGCAGCAGTGAATTATCATTTTGGCAGCAAAAAAGCACTGATTCAGGCAGTTTTTAGCCGTTTTCTGGGTCCGTTTTGTGCAAGCCTGGAACGTGAACTGGAACGTCGTCAGGCACGTCCGGAACAGAAACCGAGCCTGGAAGAACTGCTGGAAATGCTGGTTGAACAGGCACTGGCAGTTCAGCCTCGTAGCAATAATGATCTGAGCATTTTTATGCGTCTGCTGGGTCTGGCATTTAGCCAGAGCCAGGGTCATCTGCGTCGTTATCTGGAAGATATGTATGGTAAAGTGTTCCGTCGTTATATGCTGCTGGTTAATGAAGCAGCACCGCGTGTTCCGCCTCTGGAACTGTTTTGGCGTGTTCATTTTATGCTGGGTGCAGCAGCATTTAGCATGAGCGGTATTAAAGCACTGCGTGCAATTGCAGAAACCGATTTTGGTATTAACACCAGCATTGAACAGGTTATGCGTCTGATGGTTCCGTTTCTGGCAGCAGGTATGCGTGCAGATAGCGGTGTTACCGATGAAGCAATGGCAGCAGCACAGCTGCGTCCGCGTAGCAAAACCAGCACCAGCGCAACCACCGCAAAAGCATAA");
		ComponentDefinition ter11=Util.createDNAComponent(doc, "ter11", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		// Output
		ComponentDefinition ppsra=Util.createDNAComponent(doc, "ppsra", "ppsrA", "psrA promoter", SequenceOntology.PROMOTER, 
				"GGAACAAACGTTTGATTGAcagctagctcagtcctaggtataatgctagctactagag");		
		ComponentDefinition rbspsra=Util.createDNAComponent(doc, "rbspsra", "RBS_psrA", "psrA RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGGATACGAACTACTAG");
		ComponentDefinition rbs=Util.createDNAComponent(doc, "rbs", "RBS", "RBS", SequenceOntology.RIBOSOME_ENTRY_SITE,
				"CTATGGACTATGTTTGAAAGAGGATACGAACTACTAG");
		ComponentDefinition viob=Util.createDNAComponent(doc, "viob", "vioB", "vioB CDS NC_005085.1", SequenceOntology.CDS,
				"ATGAGCATTCTGGATTTTCCACGCATCCATTTCCGCGGCTGGGCGCGGGTCAACGCGCCCACCGCCAACCGCGATCCGCACGGCCACATCGACATGGCCAGCAATACGGTGGCCATGGCAGGCGAACCGTTCGACCTCGCGCGCCATCCGACCGAGTTCCACCGCCACCTGCGGTCGCTGGGGCCGCGTTTCGGCCTGGACGGCCGGGCTGACCCGGAAGGGCCGTTCAGCCTGGCCGAGGGCTACAACGCGGCCGGCAACAACCATTTCTCCTGGGAGAGCGCCACCGTCAGCCACGTGCAGTGGGATGGCGGCGAAGCGGACCGCGGCGACGGCCTGGTCGGCGCCAGGCTGGCGCTGTGGGGGCATTACAACGATTACCTGCGCACCACCTTCAACCGCGCGCGCTGGGTGGACAGCGACCCCACCCGCCGCGACGCGGCGCAGATCTACGCCGGGCAGTTCACGATCAGCCCGGCCGGCGCCGGACCGGGCACGCCCTGGCTGTTCACCGCCGACATCGACGACAGCCACGGCGCGCGCTGGACGCGCGGCGGCCACATCGCCGAGCGCGGCGGCCATTTCCTGGACGAGGAGTTCGGCCTGGCGCGGCTGTTCCAGTTCTCGGTGCCCAAAGACCATCCGCACTTCCTGTTCCACCCGGGGCCATTCGATTCCGAAGCCTGGCGCAGGCTGCAGCTGGCGCTGGAGGACGACGACGTGCTCGGCCTGACGGTGCAGTACGCGCTGTTCAATATGTCGACGCCGCCGCAACCCAACTCGCCGGTGTTCCACGACATGGTCGGCGTGGTCGGCCTGTGGCGGCGCGGCGAACTGGCCAGCTACCCGGCCGGCCGGCTGCTGCGTCCGCGCCAGCCCGGGCTGGGCGATCTGACGCTGCGCGTAAGCGGCGGCCGCGTGGCGCTGAATCTGGCCTGCGCCATTCCGTTCTCCACCCGGGCGGCGCAGCCGTCCGCGCCGGACAGGCTGACGCCCGATCTCGGGGCCAAGCTGCCGTTGGGCGACCTGCTGCTGCGCGACGAGGACGGCGCGTTGCTGGCGCGGGTGCCGCAGGCGCTTTACCAGGATTACTGGACGAACCACGGCATCGTCGACCTGCCGCTGCTGCGCGAGCCCAGGGGCTCGCTGACGCTGTCCAGCGAGCTGGCCGAATGGCGCGAGCAGGACTGGGTCACGCAGTCCGACGCCTCCAATCTTTATTTGGAAGCGCCGGACCGCCGCCACGGCCGTTTCTTTCCGGAAAGCATCGCGCTGCGCAGCTATTTCCGCGGCGAGGCCCGCGCGCGCCCGGACATTCCCCACCGGATCGAGGGGATGGGTCTGGTCGGCGTGGAGTCGCGCCAGGACGGCGATGCCGCCGAATGGCGGCTGACCGGCCTGCGGCCCGGCCCGGCGCGCATCGTGCTCGACGACGGCGCGGAGGCGATCCCGCTGCGGGTGCTGCCGGACGACTGGGCGTTGGACGACGCGACGGTGGAGGAGGTCGATTACGCCTTCCTGTACCGGCACGTGATGGCCTATTACGAGCTGGTCTACCCGTTCATGTCCGACAAGGTGTTCAGCCTGGCCGACCGCTGCAAGTGCGAGACCTACGCCAGGCTGATGTGGCAGATGTGCGATCCGCAGAACCGGAACAAGAGCTACTACATGCCCAGCACCCGCGAGCTGTCGGCGCCCAAGGCCAGGCTGTTCCTCAAATACCTGGCCCATGTCGAGGGCCAGGCCAGGCTGCAGGCGCCGCCGCCGGCCGGGCCGGCGCGCATCGAGAGCAAGGCCCAGCTGGCGGCCGAGCTGCGCAAGGCGGTGGATCTGGAGTTGTCGGTGATGCTGCAGTACCTGTACGCCGCCTATTCCATTCCCAATTACGCCCAGGGCCAGCAGCGGGTGCGCGACGGCGCGTGGACGGCGGAGCAGCTGCAGCTGGCCTGCGGCAGCGGCGACCGGCGCCGCGACGGCGGCATCCGCGCCGCGCTGCTGGAGATCGCCCACGAGGAGATGATCCATTACCTGGTGGTCAACAACCTGCTGATGGCGCTGGGCGAGCCGTTCTACGCCGGCGTGCCGCTGATGGGCGAGGCGGCGCGGCAGGCGTTCGGCCTGGACACCGAATTCGCGCTGGAGCCGTTCTCCGAGTCGACGCTGGCGCGCTTCGTCCGGCTGGAATGGCCGCACTTCATCCCTGCGCCGGGCAAATCCATCGCCGACTGCTACGCCGCCATCCGCCAGGCCTTTCTCGATCTGCCCGACCTGTTCGGCGGCGAGGCCGGCAAGCGCGGCGGCGAGCACCACTTGTTCCTCAACGAGCTGACCAACCGCGCCCATCCCGGCTACCAGCTGGAGGTGTTCGATCGCGACAGCGCGCTGTTCGGCATCGCCTTCGTCACCGACCAGGGCGAGGGCGGGGCGCTGGACTCGCCGCATTACGAGCATTCGCATTTCCAGCGGCTGCGGGAGATGTCGGCCAGGATCATGGCGCAGTCCGCGCCGTTCGAGCCGGCGTTGCCGGCGCTGCGCAACCCGGTGCTGGACGAGTCGCCGGGCTGCCAGCGCGTGGCGGACGGACGGGCGCGCGCGCTGATGGCGCTGTACCAGGGCGTGTACGAGCTGATGTTCGCGATGATGGCGCAGCACTTCGCGGTCAAGCCGCTGGGCAGCCTCAGGCGCTCGCGGCTGATGAACGCGGCGATCGACCTGATGACCGGCCTGCTCAGGCCGCTGTCCTGCGCGCTGATGAACCTGCCGTCGGGCATCGCCGGACGCACCGCCGGGCCGCCGCTGCCGGGGCCGGTGGATACCCGCAGCTACGACGACTACGCGCTGGGCTGCCGGATGCTGGCGCGGCGCTGCGAGCGCCTGCTGGAGCAGGCGTCGATGCTGGAGCCGGGCTGGCTGCCCGACGCGCAAATGGAACTGCTGGATTTCTACCGCCGGCAGATGCTGGATTTGGCTTGTGGAAAGCTTTCTAGAGAGGCCTGA");
		ComponentDefinition gfp=Util.createDNAComponent(doc, "gfp", "gfp", "gfp CDS BBa_E0040", SequenceOntology.CDS,
				"ATGCGTAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTGATGTTAATGGGCACAAATTTTCTGTCAGTGGAGAGGGTGAAGGTGATGCAACATACGGAAAACTTACCCTTAAATTTATTTGCACTACTGGAAAACTACCTGTTCCATGGCCAACACTTGTCACTACTTTCGGTTATGGTGTTCAATGCTTTGCGAGATACCCAGATCATATGAAACAGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTACAGGAAAGAACTATATTTTTCAAAGATGACGGGAACTACAAGACACGTGCTGAAGTCAAGTTTGAAGGTGATACCCTTGTTAATAGAATCGAGTTAAAAGGTATTGATTTTAAAGAAGATGGAAACATTCTTGGACACAAATTGGAATACAACTATAACTCACACAATGTATACATCATGGCAGACAAACAAAAGAATGGAATCAAAGTTAACTTCAAAATTAGACACAACATTGAAGATGGAAGCGTTCAACTAGCAGACCATTATCAACAAAATACTCCAATTGGCGATGGCCCTGTCCTTTTACCAGACAACCATTACCTGTCCACACAATCTGCCCTTTCGAAAGATCCCAACGAAAAGAGAGACCACATGGTCCTTCTTGAGTTTGTAACAGCTGCTGGGATTACACATGGCATGGATGAACTATACAAATAATAA");
		ComponentDefinition ter12=Util.createDNAComponent(doc, "ter12", "ter", "BO_4259", SequenceOntology.TERMINATOR,
				"GAAATATGATGAGCTCTCTTCTTAATGAAGGGAGTTCCGCTTTCTATAGTTGTCA");
		
		
		//TODO Add the newly create components in order here
		//Device 1
		Util.add(doc,design,pbeti1);
		Util.add(doc,design,rbsamtr1);		
		Util.add(doc,design,amtr);
		Util.add(doc,design,ter3);
		//Device 2
		ComponentDefinition design2=Util.createDNAComponent(doc, "celement2", "C-element", "C-element design", SequenceOntology.ENGINEERED_GENE);
		Util.add(doc,design2,plitr1);
		Util.add(doc,design2,rbsamtr2);		
		Util.add(doc,design2,amtr2);
		Util.add(doc,design2,ter4);
		//Device 3
		ComponentDefinition design3=Util.createDNAComponent(doc, "celement3", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		Util.add(doc,design3,pamtr);
		Util.add(doc,design3,rbssrpr1);		
		Util.add(doc,design3,srpr1);
		Util.add(doc,design3,rbsmcbr);
		Util.add(doc,design3,mcbr1);
		Util.add(doc,design3,ter5);
		//Device 4
		ComponentDefinition design4=Util.createDNAComponent(doc, "celement4", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		
		Util.add(doc,design4,psrpr);
		Util.add(doc,design4,rbsmcbr2);		
		Util.add(doc,design4,mcbr2);
		Util.add(doc,design4,rbsicar1);
		Util.add(doc,design4,icar1);
		Util.add(doc,design4,ter6);
		//Device 5
		ComponentDefinition design5=Util.createDNAComponent(doc, "celement5", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		
		Util.add(doc,design5,picar);
		Util.add(doc,design5,rbsamtr3);		
		Util.add(doc,design5,amtr3);
		Util.add(doc,design5,rbssrpr2);
		Util.add(doc,design5,srpr2);
		Util.add(doc,design5,ter7);
		//Device 6
		ComponentDefinition design6=Util.createDNAComponent(doc, "celement6", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		
		Util.add(doc,design6, pliag);
		Util.add(doc,design6,pbeti2);
		Util.add(doc,design6,plitr2);
		Util.add(doc,design6,rbsphlf);		
		Util.add(doc,design6,phlf);
		Util.add(doc,design6,ter8);
		//Device 7
		ComponentDefinition design7=Util.createDNAComponent(doc, "celement7", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		
		Util.add(doc,design7,pphlf);
		Util.add(doc,design7,rbsqacr);		
		Util.add(doc,design7,qacr);
		Util.add(doc,design7,ter9);
		//Device 8
		ComponentDefinition design8=Util.createDNAComponent(doc, "celement8", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		
		Util.add(doc,design8,pqacr);
		Util.add(doc,design8,rbsicar2);		
		Util.add(doc,design8,icar2);
		Util.add(doc,design8,ter10);
		//Device 9
		ComponentDefinition design9=Util.createDNAComponent(doc, "celement9", "", "C-element design", SequenceOntology.ENGINEERED_GENE);
		
		Util.add(doc,design9,pmcbr);
		Util.add(doc,design9,rbspsra);		
		Util.add(doc,design9,psra);
		Util.add(doc,design9,ter11);
		
		ComponentDefinition input1=Util.createDNAComponent(doc, "input1", "Input 1", "Input 1 of C-element", SequenceOntology.ENGINEERED_GENE);
		Util.add(doc,input1,pmana);
		Util.add(doc,input1,rbsmana);		
		Util.add(doc,input1,beti);
		Util.add(doc,input1,rfp);
		Util.add(doc,input1,ter1);
		
		ComponentDefinition input2=Util.createDNAComponent(doc, "input2", "Input 2", "Input 2 of C-element", SequenceOntology.ENGINEERED_GENE);
		Util.add(doc,input2,pyxeb);
		Util.add(doc,input2,rbsyxeb);		
		Util.add(doc,input2,litr);
		Util.add(doc,input2,cfp);
		Util.add(doc,input2,ter2);
		//Output
		
		ComponentDefinition output=Util.createDNAComponent(doc, "output", "Output", "Output of C-element", SequenceOntology.ENGINEERED_GENE);
		Util.add(doc,output,ppsra);
		Util.add(doc,output,rbs);		
		Util.add(doc,output,viob);
		Util.add(doc,output,gfp);
		Util.add(doc,output,ter12);
		
		ModuleDefinition moduleDef=doc.createModuleDefinition("celementmodule");
		
		//TODO Add all the other protein here
		ComponentDefinition betirfp=Util.createProteinComponent(doc, 
				"betirfp", "BetI-RFP", "BetI-RFP protein", null, null);
		ComponentDefinition litrcfp=Util.createProteinComponent(doc, 
				"litrcfp", "LitR-CFP", "LitR-CFP protein", null, null);
		ComponentDefinition amtrProtein=Util.createProteinComponent(doc, 
				"amtrprotein", "AmtR", "AmtR protein", null, null);
		ComponentDefinition srprProtein=Util.createProteinComponent(doc, 
				"srprprotein", "SrpR", "SrpR protein", null, null);
		ComponentDefinition mcbrProtein=Util.createProteinComponent(doc, 
				"mcbrprotein", "McbR", "McbR protein", null, null);
		ComponentDefinition icarProtein=Util.createProteinComponent(doc, 
				"icarprotein", "IcaR", "IcaR protein", null, null);
		ComponentDefinition phlfProtein=Util.createProteinComponent(doc, 
				"phlfprotein", "PhlF", "PhlF protein", null, null);
		ComponentDefinition qacrProtein=Util.createProteinComponent(doc, 
				"qacrprotein", "QacR", "QacR protein", null, null);
		ComponentDefinition psraProtein=Util.createProteinComponent(doc, 
				"psraprotein", "PsrA", "PsrA protein", null, null);
		ComponentDefinition viobgfp=Util.createProteinComponent(doc, 
				"viobgfp", "VioB-GFP", "VioB-GFP protein", null, null);
		
		
		
		//TODO Add all the other protein production and promoter interactions here
		Util.createTranslationInteraction(moduleDef, beti, betirfp);
		Util.createTranslationInteraction(moduleDef, litr, litrcfp);
		Util.createTranslationInteraction(moduleDef, amtr, amtrProtein);
		Util.createTranslationInteraction(moduleDef, srpr1, srprProtein);
		Util.createTranslationInteraction(moduleDef, srpr2, srprProtein);
		Util.createTranslationInteraction(moduleDef, mcbr1, mcbrProtein);
		Util.createTranslationInteraction(moduleDef, mcbr2, mcbrProtein);
		Util.createTranslationInteraction(moduleDef, icar1, icarProtein);
		Util.createTranslationInteraction(moduleDef, icar2, icarProtein);
		Util.createTranslationInteraction(moduleDef, phlf, phlfProtein);
		Util.createTranslationInteraction(moduleDef, qacr, qacrProtein);
		Util.createTranslationInteraction(moduleDef, psra, psraProtein);
		Util.createTranslationInteraction(moduleDef, viob, viobgfp);
		
		//TODO Add all the other protein production and promoter interactions here
		Util.createPromoterRepression(moduleDef, pbeti1, betirfp);
		Util.createPromoterRepression(moduleDef, pbeti2, betirfp);
		Util.createPromoterRepression(moduleDef, plitr1, litrcfp);
		Util.createPromoterRepression(moduleDef, plitr2, litrcfp);
		Util.createPromoterRepression(moduleDef, pamtr, amtrProtein);
		Util.createPromoterRepression(moduleDef, psrpr, srprProtein);
		Util.createPromoterRepression(moduleDef, picar, icarProtein);
		Util.createPromoterRepression(moduleDef, pphlf, phlfProtein);
		Util.createPromoterRepression(moduleDef, pqacr, qacrProtein);
		Util.createPromoterRepression(moduleDef, pmcbr, mcbrProtein);
		Util.createPromoterRepression(moduleDef, ppsra, psraProtein);
		
						
		Util.write(doc, new File(System.getProperty("user.home") +  "/celement.sbol"));
							
	}
}
